// creating  table movies 

CREATE TABLE movies (
    movie_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(255) NOT NULL,
    director VARCHAR2(255),
    release_year NUMBER,
    genre VARCHAR2(100),
    rating NUMBER CHECK (rating BETWEEN 0 AND 10),
    description VARCHAR2(4000)
);


// creating table directors

CREATE TABLE Directors (
    DirectorID INT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    BirthYear INT
);


//creating table genres


CREATE TABLE Genres (
    GenreID INT PRIMARY KEY,
    GenreName VARCHAR(100) NOT NULL
);


// adding  foreign keys


ALTER TABLE MOVIES ADD FOREIGN KEY (DirectorID)REFERENCES Directors(DirectorID);
ALTER TABLE MOVIES ADD FOREIGN KEY (GenreID)REFERENCES Genres(GenreID);

//  creating table reviews


CREATE TABLE Reviews (
    ReviewID INT PRIMARY KEY,
    MovieID INT,
    ReviewerName VARCHAR(255) NOT NULL,
    ReviewText VARCHAR(4000),  -- Specify a length for VARCHAR
    Rating FLOAT CHECK (Rating >= 0 AND Rating <= 10),
    ReviewDate DATE,
    FOREIGN KEY (MovieID) REFERENCES Movies(MovieID)
);

// inserting records into table directors


INSERT into directors values(2,'ezra',1948);
INSERT into directors values(3,'jean valentin',1943);
INSERT into directors values(4,'magnfique',1930);


// inserting  records into table  genres

INSERT into Genres values(1,'comedy');
INSERT INTO genres values(2,'comedy');
INSERT INTO genres values(4,'romantic');


// inserting records into table  movies


INSERT INTO movies values(1,'freinds',1,1,1990);
INSERT INTO movies values(2,'young sheldon',2,2,1995);
INSERT INTO movies values(3,'stranger things',3,3,1998);
INSERT INTO movies values(4,'the notebook',4,4,1999);


// inserting records into table  reviews


INSERT INTO reviews values(1,3,'chazzy','marvelous',9.0,TO_DATE('10-28-1998','MM-DD-YYYY'));
INSERT INTO reviews values(2,1,'gashumba','sooo good',9.3, TO_DATE('11-30-1991','MM-DD-YYYY')); 
INSERT INTO reviews values(3,2,'egide','lots of laughter',10,TO_DATE('09-05-1996','MM-DD-YYYY'));
INSERT INTO reviews values(4,4,'brian','crying rn',9,TO_DATE('08-05-2000','MM-DD-YYYY'));

// retrieving data  from tables

select*from movies;
select*from reviews;
select*from genres;
select*from directors;

// update query

update reviews
set rating=9.7
where movieid=2;

// inner join

SELECT Movies.Title, Directors.Name AS Director
FROM Movies
JOIN Directors ON Movies.DirectorID = Directors.DirectorID;

// left join

SELECT Movies.Title, Reviews.ReviewerName, Reviews.Rating
FROM Movies
LEFT JOIN Reviews ON Movies.MovieID = Reviews.MovieID;;


select*from reviews 
where rating<=10;















